In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pertanianmultinomial/Pertanianemitten.csv
/kaggle/input/pertanianmultinomial/uas.csv
/kaggle/input/pertanianmultinomial/PertanianMultinomial (1).csv
/kaggle/input/pertanianmultinomial/PertanianMultinomial.csv


In [2]:
import pandas as pd
import seaborn as sns
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [3]:
df = pd.read_csv('../input/pertanianmultinomial/uas.csv')
df.head()

DER  Operating Profit Margin  Sales Growth  Return On Asset  Category
0  0.135154                 0.135154      1.293241         0.064848         1
1  0.758859                -0.064557      0.834610        -0.064974         1
2  0.395062                 0.236027      1.625789         0.061328         2
3  0.000624                 0.227386      0.797727         0.119392         1
4  1.239184                -2.007213      1.451510        -0.059932         4

In [4]:
np.array(df)

array([[ 1.35154326e-01,  1.35154326e-01,  1.29324147e+00,
         6.48477330e-02,  1.00000000e+00],
       [ 7.58859160e-01, -6.45565480e-02,  8.34610166e-01,
        -6.49736420e-02,  1.00000000e+00],
       [ 3.95062270e-01,  2.36026568e-01,  1.62578915e+00,
         6.13284300e-02,  2.00000000e+00],
       [ 6.23580000e-04,  2.27386464e-01,  7.97726643e-01,
         1.19392284e-01,  1.00000000e+00],
       [ 1.23918365e+00, -2.00721268e+00,  1.45150996e+00,
        -5.99320140e-02,  4.00000000e+00],
       [ 3.51720847e+00, -4.12206492e-01,  1.33641854e+00,
        -1.16518174e-01,  1.00000000e+00],
       [ 5.08335265e+00,  3.31290314e-01,  1.05542852e+00,
         4.05886354e-01,  2.00000000e+00],
       [ 7.55672046e-01,  1.93574141e-01,  1.06352921e+00,
         5.30297930e-02,  4.00000000e+00],
       [ 6.24000055e-01, -3.19872460e-02,  1.05681644e+00,
        -2.64757790e-02,  1.00000000e+00],
       [ 1.06140122e+01,  5.25930500e-03,  6.37814498e-01,
        -5.52244650e-02

In [5]:
import statsmodels.api as sm

In [6]:
x = df.drop('Category', axis=1)
x.head()

DER  Operating Profit Margin  Sales Growth  Return On Asset
0  0.135154                 0.135154      1.293241         0.064848
1  0.758859                -0.064557      0.834610        -0.064974
2  0.395062                 0.236027      1.625789         0.061328
3  0.000624                 0.227386      0.797727         0.119392
4  1.239184                -2.007213      1.451510        -0.059932

In [7]:
y = df['Category']
y.head()

0    1
1    1
2    2
3    1
4    4
Name: Category, dtype: int64

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)


In [9]:
x_train_sm = sm.add_constant(x_train)
x_train_sm

const        DER  Operating Profit Margin  Sales Growth  Return On Asset
3     1.0   0.000624                 0.227386      0.797727         0.119392
18    1.0  -1.322743                 0.195796      1.263455        -0.003921
8     1.0   0.624000                -0.031987      1.056816        -0.026476
13    1.0   1.440119                 0.209131      1.898171         0.057301
17    1.0   1.645057                 0.138291      1.273060         0.042457
15    1.0   0.492060                 0.150501      1.358130         0.027361
9     1.0  10.614012                 0.005259      0.637814        -0.055224
2     1.0   0.395062                 0.236027      1.625789         0.061328
4     1.0   1.239184                -2.007213      1.451510        -0.059932
7     1.0   0.755672                 0.193574      1.063529         0.053030
10    1.0   0.000834                 0.275624      1.279567         0.083640
12    1.0   1.192419                 0.023986      1.780840         0.043147
14    1.0   0.697246                 0.279514      1.491136         0.082254
0     1.0   0.135154                 0.135154      1.293241         0.064848
1     1.0   0.758859                -0.064557      0.834610        -0.064974

In [10]:
#logit_mod = sm.Logit(y_train,x_train_sm
                     
mnlogit_mod = sm.MNLogit(y_train,x_train_sm)
mnlogit_fit = mnlogit_mod.fit()

Optimization terminated successfully.
         Current function value: 0.492140
         Iterations 12


In [11]:
print (mnlogit_fit.summary())

                          MNLogit Regression Results                          
Dep. Variable:               Category   No. Observations:                   15
Model:                        MNLogit   Df Residuals:                        5
Method:                           MLE   Df Model:                            8
Date:                Tue, 05 Jul 2022   Pseudo R-squ.:                  0.4821
Time:                        15:45:10   Log-Likelihood:                -7.3821
converged:                       True   LL-Null:                       -14.254
Covariance Type:            nonrobust   LLR p-value:                   0.08869
             Category=2       coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------
const                     -30.0354     30.669     -0.979      0.327     -90.145      30.075
DER                        -3.6444      6.231     -0.585      0.559     -15.857       8.569


In [12]:
model = LogisticRegression(multi_class='auto')
model.fit(x_train, y_train)

LogisticRegression()

In [13]:
model.predict_proba(x_test)[0:5]

array([[0.55263364, 0.1674157 , 0.27995066],
       [0.65251589, 0.21301208, 0.13447203],
       [0.73699649, 0.13129923, 0.13170427],
       [0.58551411, 0.0973894 , 0.31709649]])

In [14]:
predictions = model.predict(x_test)
predictions

array([1, 1, 1, 1])

In [15]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           1       0.50      1.00      0.67         2
           2       0.00      0.00      0.00         1
           3       0.00      0.00      0.00         1

    accuracy                           0.50         4
   macro avg       0.17      0.33      0.22         4
weighted avg       0.25      0.50      0.33         4



/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
print(accuracy_score(y_test, predictions))

0.5
